### PR TITLE
update to recent rust version

### LINKED ISSUE #6: Fails building libc with nightly
cargo build fails building libc v0.1.3 on nightly 696b7 on Linux and Windows.  Could you specify which nightly builds the current codebase?

### PR DESCRIPTION
**Pull request by pwoolcoc**
This is a pretty much mechanical translation of the `theca` code to a recent version of `rustc`. The version I compiled it with was `rustc 1.10.0 (cfcb716cf 2016-07-03)`, which as of this writing is the most recent stable version of rust. It also compiles with the latest beta and nightly.

As far as I can tell, no logic was changed. All the tests pass, and both `lib` and `bin` targets compile without warnings.

Closes #6

### CODE REVIEW

**Comment by cristicbz** [comment]
`regex!` is slower than just regular runtime `Regex`-s these days, so maybe this PR should just remove the `regex_macros` dependency entirely? For global regexes, `lazy_static` [can be used](https://doc.rust-lang.org/regex/regex/index.html).

**Comment by pwoolcoc** [comment]
@cristicbz from the looks of it, `regex_macros` isn't even being used. I can just remove it without making any code changes.

**Comment by cristicbz** [comment]
I think you could cherrypick the #8 commits if you wanted travis to pass. Though the project looks abandoned. You could create a proper fork of this and I'd use it :)

**Comment by pwoolcoc** [comment]
@cristicbz yea, I think I will do that

**Comment by pwoolcoc** [comment]
Seems there is no interest in merging this, so am closing it

**Comment by cristicbz** [comment]
@pwoolcoc :(

**Comment by pwoolcoc** [comment]
@cristicbz I have been doing improvements and bug fixes over at https://github.com/pwoolcoc/theca, if you are interested

-------- Original message --------

**Pull request closed without merging**
